from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from pipeline.core.node_base import NodeContext, pipeline_node
from pipeline.domain.dev.nodes._shared import get_goal, slugify


def _run_git(args: list[str], cwd: str) -> tuple[int, str, str]:
    completed = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    return completed.returncode, completed.stdout.strip(), completed.stderr.strip()


def _verify_ref(cwd: str, ref: str) -> bool:
    code, _, _ = _run_git(["rev-parse", "--verify", ref], cwd)
    return code == 0


def _current_branch(cwd: str) -> str:
    code, out, _ = _run_git(["branch", "--show-current"], cwd)
    return out if code == 0 and out else "HEAD"


def _resolve_base_ref(cwd: str, requested_base: str) -> str:
    candidates = [
        requested_base,
        f"origin/{requested_base}",
        "develop",
        "origin/develop",
        "main",
        "origin/main",
        _current_branch(cwd),
    ]
    for candidate in candidates:
        if candidate and _verify_ref(cwd, candidate):
            return candidate
    return "HEAD"


def _branch_exists(cwd: str, branch: str) -> bool:
    code, _, _ = _run_git(["show-ref", "--verify", f"refs/heads/{branch}"], cwd)
    return code == 0


def _create_branch_if_needed(cwd: str, branch: str, start_ref: str) -> dict:
    if _branch_exists(cwd, branch):
        return {"branch": branch, "status": "exists", "start_ref": start_ref}
    code, _, err = _run_git(["branch", branch, start_ref], cwd)
    if code == 0:
        return {"branch": branch, "status": "created", "start_ref": start_ref}
    return {"branch": branch, "status": "error", "start_ref": start_ref, "message": err}


def _pr_body(goal: str, domain: str, base_branch: str) -> str:
    return "\n".join([
        f"## Goal",
        goal,
        "",
        f"## Domain",
        domain,
        "",
        f"## Base Branch",
        base_branch,
        "",
        "## Notes",
        "- Generated by develop_branch_pr_orchestrator",
        "- Review domain-specific QA and integration QA outputs before merge",
    ])


def _write_pr_draft(cwd: str, branch: str, title: str, body: str) -> str:
    docs_dir = Path(cwd) / "DOCS" / "pr_drafts"
    docs_dir.mkdir(parents=True, exist_ok=True)
    draft_path = docs_dir / f"{branch.replace('/', '__')}.md"
    draft_path.write_text(f"# {title}\n\n{body}\n", encoding="utf-8")
    return str(draft_path)


@pipeline_node("develop_branch_pr_orchestrator")
def develop_branch_pr_orchestrator_node(ctx: NodeContext) -> dict:
    goal = get_goal(ctx.sget)
    cwd = os.getcwd()
    branch_strategy = (ctx.sget("develop_main_plan", {}) or {}).get("branch_strategy", {}) or {}
    slug = slugify(goal)[:24]
    feature_branches = branch_strategy.get("domain_branches", []) or [
        {"domain": "uiux", "branch": f"feature/{slug}-uiux"},
        {"domain": "backend", "branch": f"feature/{slug}-backend"},
        {"domain": "frontend", "branch": f"feature/{slug}-frontend"},
    ]
    requested_base = branch_strategy.get("base_branch", "develop")
    resolved_base_ref = _resolve_base_ref(cwd, requested_base)
    branch_execution = [
        {
            "domain": item["domain"],
            **_create_branch_if_needed(cwd, item["branch"], resolved_base_ref),
        }
        for item in feature_branches
    ]
    pr_plan = [
        {
            "domain": item["domain"],
            "branch": item["branch"],
            "title": f"[{item['domain']}] {goal[:60]}",
            "base": requested_base,
        }
        for item in feature_branches
    ]
    gh_available = shutil.which("gh") is not None
    pr_drafts = []
    for item in pr_plan:
        body = _pr_body(goal, item["domain"], item["base"])
        draft_path = _write_pr_draft(cwd, item["branch"], item["title"], body)
        pr_drafts.append({
            "domain": item["domain"],
            "branch": item["branch"],
            "title": item["title"],
            "draft_path": draft_path,
            "create_command": (
                f'gh pr create --base {item["base"]} --head {item["branch"]} '
                f'--title "{item["title"]}" --body-file "{draft_path}"'
            ),
        })
    merge_plan = [
        {"step": 1, "target": "uiux/frontend", "strategy": "squash"},
        {"step": 2, "target": "backend", "strategy": "squash"},
        {"step": 3, "target": "develop", "strategy": "merge-after-integration-qa"},
    ]
    has_errors = any(item.get("status") == "error" for item in branch_execution)
    gate_inputs = {
        "uiux_domain_gate": ctx.sget("uiux_domain_gate_result", {}) or {},
        "backend_domain_gate": ctx.sget("backend_domain_gate_result", {}) or {},
        "frontend_domain_gate": ctx.sget("frontend_domain_gate_result", {}) or {},
        "global_fe_sync": ctx.sget("global_fe_sync_result", {}) or {},
        "integration_qa": ctx.sget("integration_qa_result", {}) or {},
    }
    readiness_checks = []
    for name, payload in gate_inputs.items():
        status = str(payload.get("status", "")).lower()
        is_ready = status in {"", "pass", "ready"}
        readiness_checks.append({
            "check": name,
            "status": status or "unknown",
            "ready": is_ready,
            "reason": payload.get("reason", ""),
        })
    quality_blocked = any(not item["ready"] for item in readiness_checks)
    final_status = "ready"
    if has_errors or quality_blocked:
        final_status = "blocked"
    return {
        "branch_pr_result": {
            "status": final_status,
            "gitflow": "git-flow",
            "base_branch": requested_base,
            "resolved_base_ref": resolved_base_ref,
            "feature_branches": feature_branches,
            "branch_execution": branch_execution,
            "pr_plan": pr_plan,
            "pr_drafts": pr_drafts,
            "cli": {
                "gh_available": gh_available,
                "git_available": True,
            },
            "merge_plan": merge_plan,
            "readiness_checks": readiness_checks,
            "merge_ready": not has_errors and not quality_blocked,
        },
        "_thinking": "gitflow, branch-create, pr-draft",
    }
